"""Jaccard similarity between normal wScReNI and the per-TF ATAC bugfix.

Normal wScReNI reproduces the original R implementation's shared target-peak
boost. The bugfix is the per-TF motif-filtered boost previously used as the
default in ``inference.py``:

  normal   w_normal = direct_j_w + peak_j_coef + atac_boost_normal
  bugfix   w_bugfix = direct_j_w + peak_j_coef + atac_boost_bugfix

This script reads the decomposition NPZ generated by
``analyze_weight_decomposition_retina.py`` and compares the top-k edge sets of
the two networks per cell. No RF re-run is needed as long as the NPZ contains
both boost components.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--data-dir",
        default="output/weight_decomposition_retina",
        help="Directory containing decomposed_sample.npz and cell_meta.csv",
    )
    parser.add_argument("--npz-path", default=None, help="Override decomposed_sample.npz path")
    parser.add_argument("--meta-path", default=None, help="Override cell_meta.csv path")
    parser.add_argument("--top-k", type=int, default=500)
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory (default: <data-dir>/bugfix_jaccard)",
    )
    return parser.parse_args()


def top_k_set(matrix: np.ndarray, k: int) -> set[int]:
    flat = matrix.ravel(order="C")
    if k <= 0:
        raise ValueError("--top-k must be positive")
    k_eff = min(k, flat.size)
    return set(np.argpartition(flat, -k_eff)[-k_eff:].tolist())


def jaccard_and_change(a: np.ndarray, b: np.ndarray, k: int) -> tuple[float, int, int, int]:
    set_a = top_k_set(a, k)
    set_b = top_k_set(b, k)
    intersection = len(set_a & set_b)
    union = len(set_a | set_b)
    changed_per_network = len(set_a - set_b)
    return intersection / union if union else 1.0, changed_per_network, intersection, union


def load_networks(npz_path: Path) -> tuple[np.ndarray, np.ndarray, dict[str, str]]:
    with np.load(npz_path) as npz:
        files = set(npz.files)
        component_keys = {
            "direct_j_wscreni",
            "peak_j_coef",
            "atac_boost",
            "atac_boost_paper",
        }
        if component_keys.issubset(files):
            dw = npz["direct_j_wscreni"].astype(np.float32)
            pk = npz["peak_j_coef"].astype(np.float32)
            shared = dw + pk + npz["atac_boost_paper"].astype(np.float32)
            per_tf = dw + pk + npz["atac_boost"].astype(np.float32)
            source = {
                "normal": "direct_j_wscreni + peak_j_coef + atac_boost_paper",
                "bugfix": "direct_j_wscreni + peak_j_coef + atac_boost",
            }
        elif {"w_matrices_normal", "w_matrices_bugfix"}.issubset(files):
            shared = npz["w_matrices_normal"].astype(np.float32)
            per_tf = npz["w_matrices_bugfix"].astype(np.float32)
            source = {
                "normal": "w_matrices_normal",
                "bugfix": "w_matrices_bugfix",
            }
        elif {"w_matrices_paper", "w_matrices"}.issubset(files):
            shared = npz["w_matrices_paper"].astype(np.float32)
            per_tf = npz["w_matrices"].astype(np.float32)
            source = {
                "normal": "w_matrices_paper (legacy name)",
                "bugfix": "w_matrices (legacy name)",
            }
        else:
            required = {"direct_j_wscreni", "peak_j_coef"}
            if {"atac_boost_normal", "atac_boost_bugfix"}.issubset(files):
                normal_boost_name = "atac_boost_normal"
                bugfix_boost_name = "atac_boost_bugfix"
            elif {"atac_boost_paper", "atac_boost"}.issubset(files):
                normal_boost_name = "atac_boost_paper"
                bugfix_boost_name = "atac_boost"
            else:
                normal_boost_name = ""
                bugfix_boost_name = ""
            missing = sorted(required - files)
            if missing or not normal_boost_name:
                raise KeyError(
                    f"{npz_path} cannot provide normal and bugfix networks. Missing "
                    f"base arrays: {missing}. Re-run the current retinal decomposition "
                    "to store w_matrices_normal and w_matrices_bugfix."
                )
            dw = npz["direct_j_wscreni"].astype(np.float32)
            pk = npz["peak_j_coef"].astype(np.float32)
            shared = dw + pk + npz[normal_boost_name].astype(np.float32)
            per_tf = dw + pk + npz[bugfix_boost_name].astype(np.float32)
            source = {
                "normal": f"direct_j_wscreni + peak_j_coef + {normal_boost_name}",
                "bugfix": f"direct_j_wscreni + peak_j_coef + {bugfix_boost_name}",
            }
    if shared.shape != per_tf.shape or len(shared.shape) != 3:
        raise ValueError(
            f"Expected matching (cells, genes, genes) arrays, got "
            f"{shared.shape} and {per_tf.shape}"
        )
    return shared, per_tf, source


def main() -> None:
    args = parse_args()
    data_dir = Path(args.data_dir)
    npz_path = Path(args.npz_path) if args.npz_path else data_dir / "decomposed_sample.npz"
    meta_path = Path(args.meta_path) if args.meta_path else data_dir / "cell_meta.csv"
    out_dir = Path(args.out_dir) if args.out_dir else data_dir / "bugfix_jaccard"

    for path in [npz_path, meta_path]:
        if not path.exists():
            raise FileNotFoundError(path)

    shared, per_tf, source = load_networks(npz_path)
    n_cells, n_genes, _ = shared.shape

    meta = pd.read_csv(meta_path)
    cell_type_col = next(
        (col for col in ["cell_type", "subclass", "Subclass"] if col in meta.columns),
        None,
    )
    if "cell" not in meta.columns or cell_type_col is None:
        raise ValueError("cell_meta.csv must contain cell and cell-type columns")
    if len(meta) != n_cells:
        raise ValueError(f"NPZ has {n_cells} cells but metadata has {len(meta)} rows")

    print(f"Loaded {n_cells} cells × {n_genes} genes")
    print(f"Normal R-compatible network: {source['normal']}")
    print(f"Per-TF bugfix network       : {source['bugfix']}")
    print(f"Computing top-{args.top_k} Jaccard per cell")

    rows: list[dict] = []
    for i in range(n_cells):
        jac, changed, intersection, union = jaccard_and_change(shared[i], per_tf[i], args.top_k)
        rows.append({
            "cell": meta.iloc[i]["cell"],
            "cell_type": str(meta.iloc[i][cell_type_col]),
            "top_k": args.top_k,
            "jaccard_normal_vs_bugfix": round(jac, 6),
            "top_edges_shared_normal_bugfix": intersection,
            "jaccard_union_size": union,
            "edges_replaced_per_network": changed,
            "pct_edges_replaced": round(changed / min(args.top_k, n_genes * n_genes) * 100, 4),
        })

    df = pd.DataFrame(rows)
    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_dir / "bugfix_jaccard.csv", index=False)

    per_type = (
        df.groupby("cell_type")
        .agg(
            n_cells=("cell", "count"),
            mean_jaccard=("jaccard_normal_vs_bugfix", "mean"),
            sd_jaccard=("jaccard_normal_vs_bugfix", "std"),
            mean_edges_replaced=("edges_replaced_per_network", "mean"),
        )
        .reset_index()
    )
    per_type.to_csv(out_dir / "bugfix_jaccard_per_celltype.csv", index=False)

    mean_jaccard = float(df["jaccard_normal_vs_bugfix"].mean())
    sd_jaccard = float(df["jaccard_normal_vs_bugfix"].std())
    mean_replaced = float(df["edges_replaced_per_network"].mean())
    identical_cells = int((df["edges_replaced_per_network"] == 0).sum())
    interpretation = (
        "neutral" if mean_jaccard >= 0.99
        else "minor" if mean_jaccard >= 0.95
        else "material"
    )
    summary = {
        "n_cells": n_cells,
        "n_genes": n_genes,
        "top_k": args.top_k,
        "normal_wscreni_network": source["normal"],
        "per_tf_bugfix_network": source["bugfix"],
        "mean_jaccard_normal_vs_bugfix": round(mean_jaccard, 6),
        "sd_jaccard_normal_vs_bugfix": round(sd_jaccard, 6),
        "mean_edges_replaced_per_network": round(mean_replaced, 4),
        "mean_pct_edges_replaced": round(mean_replaced / min(args.top_k, n_genes * n_genes) * 100, 4),
        "n_cells_with_identical_top_k": identical_cells,
        "interpretation": interpretation,
        "note": (
            "Normal wScReNI follows the original R shared target-peak boost. "
            "The compared bugfix filters the target-peak boost per TF motif."
        ),
        "per_cell_type": {
            row["cell_type"]: {
                "n_cells": int(row["n_cells"]),
                "mean_jaccard": round(float(row["mean_jaccard"]), 6),
                "sd_jaccard": None if pd.isna(row["sd_jaccard"]) else round(float(row["sd_jaccard"]), 6),
                "mean_edges_replaced": round(float(row["mean_edges_replaced"]), 4),
            }
            for _, row in per_type.iterrows()
        },
    }
    (out_dir / "bugfix_jaccard_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    print("\nSummary")
    print(f"  Mean Jaccard(normal, bugfix): {mean_jaccard:.6f} ± {sd_jaccard:.6f}")
    print(f"  Mean replaced top-k edges   : {mean_replaced:.2f} of {args.top_k}")
    print(f"  Identical top-k cells       : {identical_cells} / {n_cells}")
    print(f"  Interpretation              : {interpretation}")
    print(f"\nSaved results to {out_dir}")


if __name__ == "__main__":
    main()
